version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "50051:50051"
    environment:
      - HF_HOME=/app/models
    volumes:
      - sd_models:/app/models
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

  client:
    build: ./client
    ports:
      - "7860:7860"
    depends_on:
      - server
    volumes:
      - ./client/gallery:/app/gallery

volumes:
  sd_models: