# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text2img.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'text2img.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etext2img.proto\x12\x08text2img\"#\n\x11GenerationRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"V\n\x12GenerationResponse\x12\x14\n\nimage_data\x18\x01 \x01(\x0cH\x00\x12 \n\x05\x65rror\x18\x02 \x01(\x0b\x32\x0f.text2img.ErrorH\x00\x42\x08\n\x06result\"&\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x32V\n\x0bTextToImage\x12G\n\x08Generate\x12\x1b.text2img.GenerationRequest\x1a\x1c.text2img.GenerationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text2img_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATIONREQUEST']._serialized_start=28
  _globals['_GENERATIONREQUEST']._serialized_end=63
  _globals['_GENERATIONRESPONSE']._serialized_start=65
  _globals['_GENERATIONRESPONSE']._serialized_end=151
  _globals['_ERROR']._serialized_start=153
  _globals['_ERROR']._serialized_end=191
  _globals['_TEXTTOIMAGE']._serialized_start=193
  _globals['_TEXTTOIMAGE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
